/**
 * Shared data loaders + cross-DB lookups. Keeps page files tidy.
 * All JSON files are generated by scripts/fetch-notion.ts at build time.
 */

// @ts-expect-error — generated
import peopleData from '../data/generated/people.json';
// @ts-expect-error — generated
import labsData from '../data/generated/labs.json';
// @ts-expect-error — generated
import projectsData from '../data/generated/projects.json';
// @ts-expect-error — generated
import softwareData from '../data/generated/software.json';
// @ts-expect-error — generated
import talksData from '../data/generated/talks.json';
// @ts-expect-error — generated
import newsData from '../data/generated/news.json';
// @ts-expect-error — generated
import eventsData from '../data/generated/events.json';
// @ts-expect-error — generated
import teachingData from '../data/generated/teaching.json';

export type Person = {
  id: string; slug: string; name: string; role: string | null;
  email: string | null; shortBio: string; longBio: string;
  interests: string[]; website: string | null; scholar: string | null;
  dblpPid: string; orcid: string; github: string; linkedin: string | null;
  status: string; order: number; photo: string | null; notes: string;
};
export type Lab = {
  id: string; slug: string; name: string; acronym: string;
  description: string; location: string;
  headIds: string[]; headText: string;
  researchLines: string[]; website: string | null;
  order: number; status: string;
};
export type Project = {
  id: string; slug: string; name: string; acronym: string;
  funding: string | null; grantId: string;
  periodStart: string | null; periodEnd: string | null;
  description: string; website: string | null;
  piIds: string[]; teamIds: string[]; labIds: string[];
  partners: string; status: string;
};
export type Software = {
  id: string; slug: string; name: string;
  shortDescription: string; longDescription: string;
  category: string | null; language: string[];
  repository: string | null; documentation: string | null;
  website: string | null; paper: string | null; pkg: string | null;
  license: string | null;
  maintainerIds: string[]; relatedProjectIds: string[]; relatedLabIds: string[];
  status: string; featured: boolean; order: number;
};
export type Talk = {
  id: string; slug: string; title: string;
  speaker: string; affiliation: string; external: boolean;
  date: string | null; timeStart: string; timeEnd: string;
  location: string; abstract: string;
  relatedLabIds: string[]; relatedPeopleIds: string[];
  postUrl: string | null; recordingUrl: string | null;
  status: string; featured: boolean;
};
export type News = {
  id: string; slug: string; title: string;
  date: string | null; excerpt: string;
  category: string | null; featured: boolean; status: string;
};

export const people   = peopleData   as Person[];
export const labs     = labsData     as Lab[];
export const projects = projectsData as Project[];
export const software = softwareData as Software[];
export const talks    = talksData    as Talk[];
export const news     = newsData     as News[];
export const events   = eventsData   as any[];
export const teaching = teachingData as any[];

/* ------------------------------------------------------------------ */
/* Lookups                                                            */
/* ------------------------------------------------------------------ */

export const peopleById   = new Map(people.map((p) => [p.id, p]));
export const labsById     = new Map(labs.map((l) => [l.id, l]));
export const projectsById = new Map(projects.map((p) => [p.id, p]));

export function personById(id: string): Person | undefined {
  return peopleById.get(id);
}
export function labById(id: string): Lab | undefined {
  return labsById.get(id);
}
export function projectById(id: string): Project | undefined {
  return projectsById.get(id);
}

/** Lab color mapping — each lab gets one of the 4 brand gradient colors. */
export function labAccent(labName: string): { bar: string; chipBg: string; chipFg: string } {
  const map: Record<string, { bar: string; chipBg: string; chipFg: string }> = {
    'MODES Lab':   { bar: '#9A1A5A', chipBg: 'color-mix(in oklch, #9A1A5A 12%, white)', chipFg: '#9A1A5A' },
    'SPENCER Lab': { bar: '#E91E5A', chipBg: 'color-mix(in oklch, #E91E5A 12%, white)', chipFg: '#E91E5A' },
    'SoSy Group':  { bar: '#F26A1F', chipBg: 'color-mix(in oklch, #F26A1F 14%, white)', chipFg: '#F26A1F' },
    'FrAmeLab':    { bar: '#FCB51A', chipBg: 'color-mix(in oklch, #FCB51A 18%, white)', chipFg: '#A06B00' },
  };
  return map[labName] ?? { bar: '#1a2332', chipBg: '#f5f3ef', chipFg: '#44546b' };
}

/** Human-readable role labels for grouping on People page. */
export const ROLE_ORDER = ['PO', 'PA', 'RTD-B', 'RTD-A', 'PostDoc', 'PhD'] as const;
export const ROLE_LABEL: Record<string, string> = {
  'PO': 'Full Professors',
  'PA': 'Associate Professors',
  'RTD-B': 'Assistant Professors (RTD-B)',
  'RTD-A': 'Assistant Professors (RTD-A)',
  'PostDoc': 'Postdocs',
  'PhD': 'PhD Students',
};

/** Initials for avatar placeholders. */
export function initials(name: string): string {
  return name.split(/\s+/).map((w) => w[0]?.toUpperCase() ?? '').slice(0, 2).join('');
}

/** Format a YYYY-MM-DD date as "MMM YYYY" (e.g. Apr 2026). */
export function fmtMonth(isoDate: string | null): string {
  if (!isoDate) return '';
  const [y, m] = isoDate.split('-');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${months[parseInt(m, 10) - 1] ?? m} ${y}`;
}

export function fmtDate(isoDate: string | null): string {
  if (!isoDate) return '';
  const [y, m, d] = isoDate.split('-');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  return `${d?.replace(/^0/, '')} ${months[parseInt(m, 10) - 1] ?? m} ${y}`;
}

/** Base URL helper (handles /website/ subpath on GitHub Pages). */
export const BASE = import.meta.env.BASE_URL.replace(/\/$/, '');
